defaults: &defaults
  docker:
    - image: circleci/node:10.12.0
  working_directory: /tmp/code

attached_workspace: &attached_workspace
  at: /tmp

version: 2
jobs:
  publish:
    <<: *defaults
    steps:
      - run: ../../tasks/publish.sh

workflows:
  version: 2
  tcweb-build:
    jobs:
      - publish:
          requires:
            - publish
          filters:
            branches:
              only:
                - master
