defaults: &defaults
  docker:
    - image: circleci/node:6.14.3
  working_directory: /tmp/code

attached_workspace: &attached_workspace
  at: /tmp

version: 2
jobs:
  release:
    <<: *defaults
    steps:
      - run: ../../tasks/release.sh

workflows:
  version: 2
  tcweb-build:
    jobs:
      - release:
          requires:
            - release
          filters:
            branches:
              only:
                - master